micronaut:
  application:
    name: hm-grunndata-compati
    thread-selection: auto
  executors:
    consumer:
      type: fixed
      nThreads: 1
  http:
    client:
      max-content-length: 100833718
      read-timeout: "5m"
      event-loop-group: http
  netty:
    event-loops:
      http:
        num-threads: 10
        prefer-native-transport: true
  server:
    max-request-size: 100833718
    port: ${SERVER_PORT:8080}
  data:
    pageable:
      max-page-size: 5000
  metrics:
    enabled: true
    binders:
      uptime:
        enabled: true
      processor:
        enabled: true
      jvm:
        enabled: true
      web:
        enabled: true
      logback:
        enabled: true
      jdbc:
        enabled: true
      kafka:
        enabled: true
    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: true
endpoints:
  metrics:
    enabled: true
  prometheus:
    sensitive: false
    enabled: true
  all:
    path: "/internal"

jackson:
  bean-introspection-module: true
  serialization:
    indentOutput: true

opensearch:
  password: ${OPEN_SEARCH_PASSWORD:admin}
  user: ${OPEN_SEARCH_USERNAME:admin}
  url: ${OPEN_SEARCH_URI:`https://localhost:9200`}

google:
  application:
    credentials: ${GOOGLE_APPLICATION_CREDENTIALS:/path/to/credential}

vertexai:
  model: ${VERTEXAI_MODEL_NAME:gemini-2.5-flash}
  location: ${VERTEXAI_LOCATION:europe-north1}
  project: ${VERTEXAI_PROJECT_ID:teamdigihot-dev-9705}
  temperature: ${VERTEXAI_TEMPERATURE:0.0f}

catalogproducts:
  aliasName: ${CATALOGPRODUCTS_ALIASNAME:catalogproducts}

grunndata:
  register:
    url: ${GRUNNDATA_REGISTER_URL:`http://localhost:8080/admreg`}

elector:
  path: ${ELECTOR_PATH:localhost}

rapidsandrivers:
  enabled: ${RAPIDSANDRIVERS_ENABLED:false}

kafka:
  topic: teamdigihot.hm-grunndata-v1
  consumerGroupId: hm-grunndata-compati-g1
  trustStorePath: ${KAFKA_TRUSTSTORE_PATH:}
  trustStorePassword: ${KAFKA_CREDSTORE_PASSWORD:}
  keystorePath: ${KAFKA_KEYSTORE_PATH:}
  keystorePassword: ${KAFKA_CREDSTORE_PASSWORD:}
  health:
    enabled: false